# Generated by Django 4.2.7 on 2025-03-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Gener',
        ),
        migrations.AddField(
            model_name='book',
            name='Gener',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Book_store.gener'),
            preserve_default=False,
        ),
    ]
